version: '3.8'

services:
  project-db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 20s
      retries: 5
    volumes:
      - project-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  project-app:
    image: notexists/kaggle-data-download-app:1.0
    depends_on:
      project-db:
        condition: service_healthy
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: host.docker.internal
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
    volumes:
      - C:\Users\HP\Desktop\TURING\Projects\Module 2\FinTech-Loan-Modeling\logs:/app/logs/

volumes:
  project-db-data:
    driver: local
  project-logs: